name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt.
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint_output=$(pylint $(git ls-files '*.py') | tee /dev/stderr)
        score=$(echo "$pylint_output" | grep -oP 'Your code has been rated at \K[0-9.]+')
        echo "Pylint score: $score"
        if (( $(echo "$score >= 9.0" | bc -l) )); then
          echo "Pylint score is $score, which is 9.0 or higher. Workflow will succeed."
          exit 0
        else
          echo "Pylint score is $score, which is below 9.0. Workflow will fail."
          exit 1
        fi
