name: Python unit testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test: 
    runs-on: ubuntu-latest
    env:
      JIRA_PROJECTS: "project1, project2"
      JIRA_API_KEY: "nothing here"
      USER_EMAIL: "nothing@here.com"
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        pip3 install pytest

    - name: Test with pytest
      run: |
        pytest -v  # Use -v for verbose output
