name: Python unit testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test: 
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: "your_email@example.com"
      JIRA_API_KEY: "your_jira_api_key"
      JIRA_LINK: "https://your_jira_instance.atlassian.net"
      GITHUB_TOKEN_READONLY_WEB: "your_github_token"
      GITHUB_METRIC_OWNER_OR_ORGANIZATION: "your_github_repo_owner"
      GITHUB_METRIC_REPO: "your_github_repo_name"
      JIRA_PROJECTS: "MYPROJECT, ENG, ETC"
      TEAM_SWE: "Swedes" 
      CUSTOM_FIELD_TEAM: "10075"
      CUSTOM_FIELD_WORK_TYPE: "10079"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install gql pytest jira pytest-cov
        
    - name: Test with pytest
      run: |
        #pytest -v --junitxml=unittests.xml --cov=jira_metrics --cov-report=xml --cov-branch --cov-fail-under=50
        pytest --cov --junitxml=junit.xml -o junit_family=legacy --cov-branch --cov-fail-under=50
    
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
